name: 'check links in the modified content validity'
description: 'get modified content'
inputs:
  token:
    description: "Token used to close a pull request if there is invalid link"
      required: false
      default: ${{ github.token }}
outputs:
  validity: 
    description: 'The validity of the links in the modified content'
runs:
  using: 'node12'
  main: 'index.js'
