name: 'get modified content'
description: 'get modified content'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
  time: # id of output
    description: 'The time output'
runs:
  using: 'node12'
  main: 'index.js'
