name: 'get modified content'
description: 'get modified content'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
  content: # id of output
    description: 'The content of the modified information'
runs:
  using: 'node12'
  main: 'index.js'
