name: 'check links in the modified content validity'
description: 'get modified content'
inputs:
  token:  
    description: 'github user token'
    required: true
outputs:
  validity: 
    description: 'The validity of the links in the modified content'
runs:
  using: 'node12'
  main: 'index.js'
