name: 'check links in the modified content validity'
description: 'get modified content'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
  validity: 
    description: 'The validity of the links in the modified content'
runs:
  using: 'node12'
  main: 'index.js'
